name: nerfstudio_test
channels:
  - nvidia/label/cuda-11.8.0
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libffi=3.4.4=hd77b12b_1
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - nsight-compute=2022.3.0.22=0
  - openssl=3.0.16=h3f729d1_0
  - python=3.10.16=h4607a30_1
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - vc=14.42=haa95532_4
  - vs2015_runtime=14.42.34433=he0abc0d_4
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - absl-py==2.2.2
      - accelerate==0.19.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - av==14.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bidict==0.23.1
      - bitsandbytes==0.43.0
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - colorlog==6.9.0
      - comet-ml==3.49.7
      - comm==0.2.2
      - configargparse==1.7
      - configobj==5.0.9
      - contourpy==1.3.1
      - cryptography==44.0.2
      - cuda-backend==0.0.0
      - cycler==0.12.1
      - dash==3.0.2
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - diffusers==0.16.1
      - dill==0.3.9
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - dulwich==0.22.8
      - everett==3.1.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fire==0.7.0
      - flask==3.0.3
      - fonttools==4.57.0
      - fpsample==0.3.3
      - fqdn==1.5.1
      - fsspec==2025.3.2
      - gdown==5.2.0
      - gin-config==0.5.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.71.0
      - gsplat==1.5.0
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.8
      - httpx==0.28.1
      - huggingface-hub==0.25.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.6.1
      - ipykernel==6.29.5
      - ipython==8.35.0
      - ipywidgets==8.1.6
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.3.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.14
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - lxml==5.3.2
      - manifold3d==3.0.1
      - mapbox-earcut==1.0.3
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.2
      - mistune==3.1.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgpack-numpy==0.4.8
      - msgspec==0.19.0
      - msvc-runtime==14.42.34433
      - multiprocess==0.70.17
      - narwhals==1.34.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nerfacc==0.5.3
      - nerfstudio==1.1.5
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nodeenv==1.9.1
      - notebook==7.4.0
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nuscenes-devkit==1.1.9
      - open3d==0.19.0
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.10.0.84
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathos==0.3.3
      - pillow==11.1.0
      - pip==25.0.1
      - platformdirs==4.3.7
      - plotly==6.0.1
      - plyfile==1.1
      - pox==0.3.5
      - ppft==1.7.6.9
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==3.20.3
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pycocotools==2.0.8
      - pycollada==0.9
      - pycparser==2.22
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pygments==2.19.1
      - pymeshlab==2023.12.post1
      - pyngrok==7.2.3
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - python-engineio==4.11.2
      - python-json-logger==3.3.0
      - python-socketio==5.12.1
      - pytorch-msssim==1.0.0
      - pytz==2025.2
      - pywin32==310
      - pywinpty==2.0.15
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - rawpy==0.24.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.24.0
      - rtree==1.4.0
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.1.99
      - sentry-sdk==2.25.1
      - setproctitle==1.3.5
      - setuptools==78.1.0
      - shapely==2.1.0
      - shtab==1.7.1
      - simple-websocket==1.1.0
      - simplejson==3.20.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - splatfacto-w==0.1.5
      - splines==0.3.0
      - stack-data==0.6.3
      - svg-path==6.3
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorly==0.9.0
      - termcolor==3.0.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - timm==0.6.7
      - tinycss2==1.4.0
      - tinycudann==1.7
      - tokenizers==0.13.3
      - tomli==2.2.1
      - torch==2.1.2+cu118
      - torch-fidelity==0.3.0
      - torch-scatter==2.1.2
      - torchmetrics==1.7.1
      - torchvision==0.16.2+cu118
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.29.2
      - trimesh==4.6.6
      - typeguard==4.4.2
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tyro==0.8.12
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.4.0
      - vhacdx==0.0.8.post2
      - viser==0.2.7
      - wadler-lindig==0.1.4
      - wandb==0.19.9
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - wsproto==1.2.0
      - wurlitzer==3.1.1
      - xatlas==0.0.10
      - xxhash==3.5.0
      - yourdfpy==0.0.57
      - zipnerf==0.1.0
      - zipp==3.21.0
prefix: C:\Users\crist\anaconda3\envs\nerfstudio_test
